demo.service.version: 1.0.0
dubbo:
  application:
    name: dubbo-provider
    register-mode: instance
  protocol:
    name: dubbo
    port: 20880
#  registry:
#    address: zookeeper://localhost:2181

  registries:
    zookeeper2181:
      register: true
      address: zookeeper://localhost:2181
    zookeeper2182:
      register: true
      address: zookeeper://localhost:2182
  provider:
    timeout: 10000
